# -*- coding: utf-8 -*-
"""Table des matières : source unique pour le PDF et pour le site."""

TITRE = "Couleurs cubaines"
SOUS_TITRE = "Méthode de guitare classique pour débutant · 8 semaines, 20 minutes par jour"

SECTIONS = [
    dict(n=1,  slug="mode-emploi",
         kicker="Avant de commencer",
         title="Comment utiliser ce guide",
         sub="Trois règles, une routine, et la permission de mal jouer.",
         desc="la méthode, la routine, l'état d'esprit"),
    dict(n=2,  slug="accordage",
         kicker="Fondations",
         title="Accorder sa guitare",
         sub="Une guitare désaccordée sabote l'oreille avant même la première note.",
         desc="pas à pas, avec et sans accordeur"),
    dict(n=3,  slug="solfege",
         kicker="Fondations",
         title="Juste assez de solfège",
         sub="Do–Ré–Mi et C–D–E sont deux noms pour les mêmes sept notes.",
         desc="les deux notations, le manche, la gamme"),
    dict(n=4,  slug="accords",
         kicker="Le socle",
         title="Les huit accords de base",
         sub="Tu les connais déjà. On va les connaître mieux.",
         desc="diagrammes, doigtés, pièges, sonorités"),
    dict(n=5,  slug="enchainements",
         kicker="Le socle",
         title="Réussir ses enchaînements",
         sub="Le vrai sujet n'est pas l'accord : c'est le trajet entre deux accords.",
         desc="doigts pivots, changements à la minute, grilles"),
    dict(n=6,  slug="arpege",
         kicker="Main droite",
         title="La technique de l'arpège",
         sub="P·I·M·A : quatre doigts, une mécanique, mille couleurs.",
         desc="PIMA, tirando, apoyando, patrons"),
    dict(n=7,  slug="rythme",
         kicker="Main droite",
         title="Rythme et lecture rythmique",
         sub="La musique, c'est du temps organisé. Apprenons à le lire.",
         desc="valeurs, silences, mesures, clave écrite"),
    dict(n=8,  slug="couleurs-cubaines",
         kicker="Le voyage",
         title="Les couleurs cubaines",
         sub="Clave, boléro, guajira, son : d'où vient ce balancement.",
         desc="clave, tresillo, boléro, guajira, son"),
    dict(n=9,  slug="programme",
         kicker="Le voyage",
         title="Le programme des 8 semaines",
         sub="Huit semaines, cinquante-six séances, une progression sans trou.",
         desc="semaine par semaine, séance par séance"),
    dict(n=10, slug="piece",
         kicker="Le voyage",
         title="Ta première pièce cubaine",
         sub="« Guajira sencilla » — écrite pour tes huit accords.",
         desc="la pièce complète, en tablature et en grille"),
    dict(n=11, slug="glossaire",
         kicker="Références",
         title="Glossaire technique",
         sub="Tous les mots du guide, rangés par ordre alphabétique.",
         desc="tous les termes du guide"),
    dict(n=12, slug="carnet",
         kicker="Références",
         title="Carnet de suivi",
         sub="Ce qui se mesure s'améliore. Ce qui s'écrit ne se perd pas.",
         desc="tableaux à remplir, 8 semaines"),
    dict(n=13, slug="pour-aller-plus-loin",
         kicker="Références",
         title="Pour aller plus loin",
         sub="Ce que tu pourras attaquer à la neuvième semaine.",
         desc="répertoire, ressources, suite du parcours"),
]

def by_slug(slug):
    for s in SECTIONS:
        if s["slug"] == slug:
            return s
    raise KeyError(slug)
